### ISSUE TITLE
使用各种mapping属性都没法实现一页一discussion

### ISSUE THREAD

**Issue by Maicarons** [mg0324/docsify-giscus#1]
你好,开发者,

[代码](https://github.com/Maicarons/livelawhelper/blob/80daac5b354a1bf9fca53c9f28531c7cb2900dd4/index.html#L56-L70)

使用各种mapping属性都没法实现一页一discussion.请问如何设置?

**Comment by mg0324** [comment]
请参考 https://giscus.app/zh-CN  页面和discussion的关系，一般使用url，或者title即可。

页面 ↔️ discussion 映射关系
选择页面与嵌入的 discussion 之间的映射关系。


Discussion 的标题包含页面的 pathname
giscus 将查找标题中包含页面 URL 的 pathname 部分的 discussion。

Discussion 的标题包含页面的 URL
giscus 将查找标题中包含页面 URL 的 discussion。

Discussion 的标题包含页面的 <title>
giscus 将查找标题中包含页面的 <title> 标签的 discussion。

Discussion 的标题包含页面的 og:title
giscus 将查找标题中包含页面的 [<meta property="og:title">](https://ogp.me/) 标签的 discussion。

Discussion 的标题包含特定字符串
giscus 将查找标题中包含特定字符串的 discussion。

特定 discussion 号
giscus 将按编号加载特定的 discussion。该选项不支持自动创建 discussion。

使用严格的标题匹配
当有多个具有相似标题的讨论时，避免由于 GitHub 的模糊搜索方法而导致的不匹配。查看[文档](https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#data-strict)获取更多细节。
